# Generated by Django 3.2.16 on 2022-11-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('weekday', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
