# Generated by Django 3.2.16 on 2022-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(blank=True, default='no information', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, default='no information', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='weekday',
            field=models.CharField(blank=True, default='no information', max_length=255, null=True),
        ),
    ]
